### ISSUE TITLE
Access to the data

### ISSUE THREAD

**Issue by ray8828** [garvita-tiwari/neuralgif#1]
Hi, thanks for sharing this great work.
The data folder in the link is empty, when could we get access to the dataset? thanks!!

**Comment by garvita-tiwari** [comment]
Hi, we apologise for the delay. I have added the data(scans and registrations).
{ClothingStyle}/scans -> contains  raw scans ({frame_ids.obj})
{ClothingStyle}/smpl_registrations.npz -> contains SMPL+D registrations for each frame.
smpl_registrations.npz contains following:
betas-> smpl betas
thetas->smpl pose
trans->smpl trans
vh-> high resolution smpl vertices
frames-> frame ids of sequence
