### ISSUE TITLE
prepare_data/scan_data.py is missing

### ISSUE THREAD

**Issue by StevenLiuWen** [garvita-tiwari/neuralgif#2]
Hi, researchers,

Thanks for the released code of this excellent work.

It seems that the file of prepare_data/scan_data.py is missing, and also the [data folder](https://nextcloud.mpi-klsb.mpg.de/index.php/s/FweAP5Js58Q9tsq?path=%2Fdata) is empty.

**Comment by garvita-tiwari** [comment]
#1

**Comment by bluestyle97** [comment]
So where is scan_data.py?
