### ISSUE TITLE
Code 

### ISSUE THREAD

**Issue by HDYYZDN** [garvita-tiwari/neuralgif#3]
您好，Data preparation的 SMPL pose and shape parameters:  https://github.com/bharat-b7/IPNet ，是按照 IPNet 安装环境吗？而且在prepare_data没有发现 scan_data.py文件

**Comment by garvita-tiwari** [comment]
scan_data.py is named as clothseq_data.py
I have corrected the README file. 
Also for ClothSeq data, I have provided SMPL registrations, so you don't need to run IPNet registrations.
