### ISSUE TITLE
Missing files in load_data.py

### ISSUE THREAD

**Issue by bluestyle97** [garvita-tiwari/neuralgif#6]
Hi, in [models/load_data.py#36](https://github.com/garvita-tiwari/neuralgif/blob/main/models/load_data.py#L36), it loads `skinning_body.npy` and `000_tpose.npy`, but I did't find these 2 files in the released data. Where do they come from? Thanks.

**Comment by garvita-tiwari** [comment]
Hi, 
I have added these files in the folder data_files/

(https://github.com/garvita-tiwari/neuralgif/tree/main/data_files)
